os: osx
osx_image: xcode12.2
language: swift
script: 
  - xcodebuild clean build test -project EssentialFeed/EssentialFeed2.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
  - xcodebuild clean build test -workspace EssentialApp/EssentialApp.workspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS simulator,OS=14.2,name=iPhone 12" ONLY_ACTIVE_ARCH=YES
