os: osx
osx_image: xcode13.3
language: swift
script: 
  - xcodebuild clean build test -project EssentialFeed/EssentialFeed2.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
  - xcodebuild clean build test -workspace EssentialApp/EssentialApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS simulator,OS=15.4,name=iPhone 13" ONLY_ACTIVE_ARCH=YES
